// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/stonecutter/blog-microservices/api/protobuf"
	"github.com/stonecutter/blog-microservices/internal/comment"
	"github.com/stonecutter/blog-microservices/internal/pkg/config"
	"github.com/stonecutter/blog-microservices/internal/pkg/dbcontext"
	"github.com/stonecutter/blog-microservices/internal/pkg/log"
	"github.com/stonecutter/blog-microservices/internal/post"
	"github.com/stonecutter/blog-microservices/internal/user"
)

// Injectors from wire.go:

func InitServer(logger *log.Logger, conf *config.Config) (protobuf.CommentServiceServer, error) {
	db, err := dbcontext.NewCommentDB(conf)
	if err != nil {
		return nil, err
	}
	repository := comment.NewRepository(logger, db)
	userServiceClient, err := user.NewClient(logger, conf)
	if err != nil {
		return nil, err
	}
	postServiceClient, err := post.NewClient(logger, conf)
	if err != nil {
		return nil, err
	}
	commentServiceServer := comment.NewServer(logger, repository, userServiceClient, postServiceClient)
	return commentServiceServer, nil
}
