// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jxlwqq/blog-microservices/api/protobuf/blog/v1"
	"github.com/jxlwqq/blog-microservices/internal/auth"
	"github.com/jxlwqq/blog-microservices/internal/blog"
	"github.com/jxlwqq/blog-microservices/internal/comment"
	"github.com/jxlwqq/blog-microservices/internal/pkg/config"
	"github.com/jxlwqq/blog-microservices/internal/pkg/log"
	"github.com/jxlwqq/blog-microservices/internal/post"
	"github.com/jxlwqq/blog-microservices/internal/user"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func InitServer(logger log.Logger, conf *config.Config) (v1.BlogServiceServer, error) {
	userServiceClient, err := user.NewClient(logger, conf)
	if err != nil {
		return nil, err
	}
	postServiceClient, err := post.NewClient(logger, conf)
	if err != nil {
		return nil, err
	}
	commentServiceClient, err := comment.NewClient(logger, conf)
	if err != nil {
		return nil, err
	}
	authServiceClient, err := auth.NewClient(logger, conf)
	if err != nil {
		return nil, err
	}
	blogServiceServer := blog.NewServer(logger, conf, userServiceClient, postServiceClient, commentServiceClient, authServiceClient)
	return blogServiceServer, nil
}
