// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/stonecutter/blog-microservices/api/protobuf"
	"github.com/stonecutter/blog-microservices/internal/auth"
	"github.com/stonecutter/blog-microservices/internal/pkg/config"
	"github.com/stonecutter/blog-microservices/internal/user"
)

// Injectors from wire.go:

func InitServer(conf *config.Config) (protobuf.AuthServiceServer, error) {
	userServiceClient, err := user.NewClient(conf)
	if err != nil {
		return nil, err
	}
	jwtManager := auth.NewJWTManager(conf)
	authServiceServer := auth.NewServer(userServiceClient, jwtManager)
	return authServiceServer, nil
}
