apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dtm-server
    version: v1
  name: dtm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dtm-server
      version: v1
  template:
    metadata:
      labels:
        app: dtm-server
        version: v1
    spec:
      containers:
        - name: dtm-server
          image: yedf/dtm:1.11
          imagePullPolicy: IfNotPresent
          args:
            - "-c=/app/dtm/configs/config.yaml"
          volumeMounts:
            - mountPath: /app/dtm/configs
              name: config
          ports:
            - containerPort: 36789
              protocol: TCP
              name: http
            - containerPort: 36790
              protocol: TCP
              name: grpc
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 36789
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 36789
              scheme: HTTP
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
      volumes:
        - name: config
          configMap:
            name: dtm-config
---
apiVersion: v1
kind: Service
metadata:
  name: dtm-server
  labels:
    app: dtm-server
spec:
  ports:
    - port: 36790
      targetPort: 36790
      name: grpc
      appProtocol: grpc
    - port: 36789
      targetPort: 36789
      name: http
      appProtocol: http
  selector:
    app: dtm-server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dtm-config
  labels:
    app: dtm-server
data:
  config.yaml: |-
    Store:
      Driver: mysql
      Host: dtm-db
      Port: 3306
      User: root
      Password: ''